'use client';

import {
  Archive,
  Check,
  Code2,
  Copy,
  Download,
  ExternalLink,
  FileCode,
  FileText,
  Printer,
  Sparkles,
} from 'lucide-react';
import React, { useState } from 'react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { generatePlainTextResume } from '@/lib/plainTextResume';
import { downloadZip, triggerFileDownload } from '@/lib/zip';

interface ExportSuiteModalProps {
  isOpen: boolean;
  onOpenChange: (open: boolean) => void;
  resumeData: any;
  latexCode?: string;
  downloadUrl?: string | null;
  candidateName?: string;
}

export const ExportSuiteModal: React.FC<ExportSuiteModalProps> = ({
  isOpen,
  onOpenChange,
  resumeData,
  latexCode = '',
  candidateName = 'Resume',
}) => {
  const [copiedFormat, setCopiedFormat] = useState<string | null>(null);

  const safeFilenameBase = (candidateName || 'Candidate')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');

  const handleCopy = (text: string, formatId: string) => {
    navigator.clipboard.writeText(text);
    setCopiedFormat(formatId);
    setTimeout(() => setCopiedFormat(null), 2000);
  };

  const handlePrintPdf = () => {
    onOpenChange(false);
    setTimeout(() => {
      window.print();
    }, 300);
  };

  const handleDownloadTex = () => {
    triggerFileDownload(`${safeFilenameBase}_resume.tex`, latexCode, 'application/x-tex');
  };

  const handleDownloadTxt = () => {
    const plainText = generatePlainTextResume(resumeData);
    triggerFileDownload(`${safeFilenameBase}_resume.txt`, plainText, 'text/plain');
  };

  const handleDownloadJson = () => {
    const jsonStr = JSON.stringify(resumeData, null, 2);
    triggerFileDownload(`${safeFilenameBase}_resume.json`, jsonStr, 'application/json');
  };

  const handleDownloadZip = () => {
    const plainText = generatePlainTextResume(resumeData);
    const jsonStr = JSON.stringify(resumeData, null, 2);
    const readme = `# ${candidateName} — Tailored Resume Package

This archive contains your tailored, audited resume generated by Praman.

## Files Included:
- **resume.tex**: Primary LaTeX source code.
- **resume.json**: Audited ground-truth evidence data with verification stamps.
- **resume.txt**: Clean ASCII text formatted for online application portals.

## Compilation Instructions:
To compile into a PDF locally:
\`\`\`bash
# Standard TeX Live / MacTeX / MiKTeX
pdflatex resume.tex
# Or with XeLaTeX
xelatex resume.tex
\`\`\`

## Cloud Editing:
You can also upload this archive directly to [Overleaf](https://www.overleaf.com) via 'New Project' -> 'Upload Project'.
`;

    downloadZip(`${safeFilenameBase}_resume_bundle.zip`, {
      'resume.tex': latexCode,
      'resume.json': jsonStr,
      'resume.txt': plainText,
      'README.md': readme,
    });
  };

  const handleOpenOverleaf = () => {
    // Zero-failure POST submission to Overleaf
    const form = document.createElement('form');
    form.method = 'POST';
    form.action = 'https://www.overleaf.com/docs';
    form.target = '_blank';

    const input = document.createElement('input');
    input.type = 'hidden';
    input.name = 'snip';
    input.value = latexCode;

    form.appendChild(input);
    document.body.appendChild(form);
    form.submit();
    document.body.removeChild(form);
  };

  return (
    <Dialog open={isOpen} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-2xl bg-card border-border max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <div className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg bg-brand-cyan/10 border border-brand-cyan/30 flex items-center justify-center text-brand-cyan">
              <Download className="w-4 h-4" />
            </div>
            <div>
              <DialogTitle className="text-lg font-bold text-foreground">
                Export Resume Suite
              </DialogTitle>
              <DialogDescription className="text-xs text-muted-foreground">
                Choose from multiple high-fidelity formats tailored for recruiters, cloud IDEs, and
                ATS portals.
              </DialogDescription>
            </div>
          </div>
        </DialogHeader>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-3.5 py-3">
          {/* 1. PDF Document */}
          <div className="p-4 rounded-xl border border-border bg-muted/20 hover:border-brand-cyan/40 transition flex flex-col justify-between space-y-3">
            <div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Printer className="w-4 h-4 text-brand-cyan" />
                  <h4 className="text-sm font-semibold text-foreground">Formatted PDF</h4>
                </div>
                <Badge
                  variant="outline"
                  className="text-[10px] bg-brand-cyan/10 border-brand-cyan/30 text-brand-cyan font-mono"
                >
                  PRINT / PDF
                </Badge>
              </div>
              <p className="text-xs text-muted-foreground mt-1.5 leading-relaxed">
                Direct A4 document print with isolated print styling. Ideal for immediate recruiter
                submissions.
              </p>
            </div>
            <Button
              size="sm"
              onClick={handlePrintPdf}
              className="w-full bg-brand-cyan hover:bg-brand-cyan/90 text-brand-dark font-semibold text-xs gap-1.5 shadow-xs"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / Save as PDF</span>
            </Button>
          </div>

          {/* 2. Overleaf Cloud Launch */}
          <div className="p-4 rounded-xl border border-border bg-muted/20 hover:border-brand-pink/40 transition flex flex-col justify-between space-y-3">
            <div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <ExternalLink className="w-4 h-4 text-brand-pink" />
                  <h4 className="text-sm font-semibold text-foreground">Overleaf Cloud</h4>
                </div>
                <Badge
                  variant="outline"
                  className="text-[10px] bg-brand-pink/10 border-brand-pink/30 text-brand-pink font-mono"
                >
                  1-CLICK IDE
                </Badge>
              </div>
              <p className="text-xs text-muted-foreground mt-1.5 leading-relaxed">
                Instantly loads your tailored LaTeX into a new Overleaf project with zero CORS or
                auth limits.
              </p>
            </div>
            <Button
              size="sm"
              onClick={handleOpenOverleaf}
              className="w-full bg-brand-pink hover:bg-brand-pink/90 text-white font-semibold text-xs gap-1.5 shadow-xs"
            >
              <Sparkles className="w-3.5 h-3.5" />
              <span>Open in Overleaf</span>
            </Button>
          </div>

          {/* 3. LaTeX Source Code (.tex) */}
          <div className="p-4 rounded-xl border border-border bg-muted/20 hover:border-border/80 transition flex flex-col justify-between space-y-3">
            <div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <FileCode className="w-4 h-4 text-brand-cyan" />
                  <h4 className="text-sm font-semibold text-foreground">LaTeX Source (.tex)</h4>
                </div>
                <Badge
                  variant="outline"
                  className="text-[10px] bg-muted border-border text-muted-foreground font-mono"
                >
                  SOURCE CODE
                </Badge>
              </div>
              <p className="text-xs text-muted-foreground mt-1.5 leading-relaxed">
                Standalone source file containing preamble, styles, and full tailored resume
                sections.
              </p>
            </div>
            <div className="flex items-center gap-2">
              <Button
                size="sm"
                variant="outline"
                onClick={handleDownloadTex}
                className="flex-1 text-xs border-border gap-1.5 bg-card hover:bg-muted"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download .tex</span>
              </Button>
              <Button
                size="sm"
                variant="outline"
                onClick={() => handleCopy(latexCode, 'tex')}
                className="px-2.5 text-xs border-border bg-card hover:bg-muted"
                title="Copy LaTeX Code"
              >
                {copiedFormat === 'tex' ? (
                  <Check className="w-3.5 h-3.5 text-brand-cyan" />
                ) : (
                  <Copy className="w-3.5 h-3.5" />
                )}
              </Button>
            </div>
          </div>

          {/* 4. Full ZIP Project Bundle */}
          <div className="p-4 rounded-xl border border-border bg-muted/20 hover:border-border/80 transition flex flex-col justify-between space-y-3">
            <div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Archive className="w-4 h-4 text-amber-500" />
                  <h4 className="text-sm font-semibold text-foreground">Project Bundle (.zip)</h4>
                </div>
                <Badge
                  variant="outline"
                  className="text-[10px] bg-amber-500/10 border-amber-500/30 text-amber-500 font-mono"
                >
                  PACKAGE
                </Badge>
              </div>
              <p className="text-xs text-muted-foreground mt-1.5 leading-relaxed">
                Complete archive containing .tex code, JSON data, and README with compilation
                commands.
              </p>
            </div>
            <Button
              size="sm"
              variant="outline"
              onClick={handleDownloadZip}
              className="w-full text-xs border-border gap-1.5 bg-card hover:bg-muted"
            >
              <Download className="w-3.5 h-3.5 text-amber-500" />
              <span>Download .zip Package</span>
            </Button>
          </div>

          {/* 5. ATS Plain Text (.txt) */}
          <div className="p-4 rounded-xl border border-border bg-muted/20 hover:border-border/80 transition flex flex-col justify-between space-y-3">
            <div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <FileText className="w-4 h-4 text-emerald-400" />
                  <h4 className="text-sm font-semibold text-foreground">ATS Plain Text (.txt)</h4>
                </div>
                <Badge
                  variant="outline"
                  className="text-[10px] bg-emerald-500/10 border-emerald-500/30 text-emerald-400 font-mono"
                >
                  ASCII TEXT
                </Badge>
              </div>
              <p className="text-xs text-muted-foreground mt-1.5 leading-relaxed">
                Clean text without markup, optimized for pasting into online career application
                forms.
              </p>
            </div>
            <div className="flex items-center gap-2">
              <Button
                size="sm"
                variant="outline"
                onClick={handleDownloadTxt}
                className="flex-1 text-xs border-border gap-1.5 bg-card hover:bg-muted"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download .txt</span>
              </Button>
              <Button
                size="sm"
                variant="outline"
                onClick={() => handleCopy(generatePlainTextResume(resumeData), 'txt')}
                className="px-2.5 text-xs border-border bg-card hover:bg-muted"
                title="Copy Plain Text"
              >
                {copiedFormat === 'txt' ? (
                  <Check className="w-3.5 h-3.5 text-emerald-400" />
                ) : (
                  <Copy className="w-3.5 h-3.5" />
                )}
              </Button>
            </div>
          </div>

          {/* 6. Ground-Truth Ledger (.json) */}
          <div className="p-4 rounded-xl border border-border bg-muted/20 hover:border-border/80 transition flex flex-col justify-between space-y-3">
            <div>
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Code2 className="w-4 h-4 text-cyan-400" />
                  <h4 className="text-sm font-semibold text-foreground">Verified Data (.json)</h4>
                </div>
                <Badge
                  variant="outline"
                  className="text-[10px] bg-cyan-500/10 border-cyan-500/30 text-cyan-400 font-mono"
                >
                  JSON SCHEMA
                </Badge>
              </div>
              <p className="text-xs text-muted-foreground mt-1.5 leading-relaxed">
                Raw structured resume JSON with confirmed evidence references and source IDs.
              </p>
            </div>
            <div className="flex items-center gap-2">
              <Button
                size="sm"
                variant="outline"
                onClick={handleDownloadJson}
                className="flex-1 text-xs border-border gap-1.5 bg-card hover:bg-muted"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download .json</span>
              </Button>
              <Button
                size="sm"
                variant="outline"
                onClick={() => handleCopy(JSON.stringify(resumeData, null, 2), 'json')}
                className="px-2.5 text-xs border-border bg-card hover:bg-muted"
                title="Copy JSON"
              >
                {copiedFormat === 'json' ? (
                  <Check className="w-3.5 h-3.5 text-cyan-400" />
                ) : (
                  <Copy className="w-3.5 h-3.5" />
                )}
              </Button>
            </div>
          </div>
        </div>

        <DialogFooter showCloseButton={false}>
          <DialogClose render={<Button variant="outline" size="sm" type="button" />}>
            Close
          </DialogClose>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};
